### ISSUE TITLE
Add a sample of Cairo project on the Starknet blockchain

### ISSUE THREAD

**Issue by wangeguo** [amp-buildpacks/samples#5]
Please help us make a simple sample project in the `/cairo/starknet/` directory, preferably a more standard project on the Starknet chain, that expresses as much as possible the effectiveness of the tools used in the Starknet build process.

Reference: [Add a sample of Move's project on the Sui blockchain](https://github.com/amp-buildpacks/samples/commit/77842a85e5450b07af032fa6a64cd772f1280178)

**Comment by zouyuxuan** [comment]
I'll take this issue
